### ISSUE TITLE
Disk Crucial X8 2TB Portable SSD isn't recognized by TinWoo

### ISSUE THREAD

**Issue by Informartiste** [mrdude2478/TinWoo#16]
I use DeepSea with Atmosphere 1.3.0 and TinWoo 1.04.
My Crucial X8 2TB Portable SSD isn't recognized by TinWoo.
I tried with the drive formated in exFat then in NTFS, TinWoo keeps saying: "USB HDD is not connected".
And my filesystem is clean.

It works with my Samsung Portable SSD T5 (500 Go) in NTFS.

Thanks for your work !

**Comment by mrdude2478** [comment]
Try using DBI installer, it's far more advanced than this installer.

https://github.com/rashevskyv/dbi

**Comment by Informartiste** [comment]
Thanks, for tour answer, I will take a look.
Why DeepSea (even the latest one) still uses your installer if even you, you recommend another one ?

Have a good day

**Comment by Informartiste** [comment]
DBI is not open source, it could be a problem.

**Comment by mrdude2478** [comment]
I am finished modding this app now and have only put it up so others can mess about with it. I now use DBI installer as that's more advanced.
