### ISSUE TITLE
1.0.5 in Japanese, no setting to switch back to English?

### ISSUE THREAD

**Issue by eyeonus** [mrdude2478/TinWoo#19]
I can't read Japanese.

Tried deleting the config and relaunching, still in Japanese.

**Comment by eyeonus** [comment]
To be clear, Tinwoo was in English before the in-app update.

**Comment by mrdude2478** [comment]
Go to the settings page, click on the third line from the bottom - Language and then select En, the app will close. When you restart it will be in English.

**Comment by Jayinem** [comment]
Mine updated and is in Japanese, but the language is already listed as english? I tried choosing en anyway, in fact I tried every language but it still is in Japanese. I even tried deleting Tinwoo all together and reinstalling it but it's still in Japanese. WTF

**Comment by mrdude2478** [comment]
> Mine updated and is in Japanese, but the language is already listed as english? I tried choosing en anyway, in fact I tried every language but it still is in Japanese. I even tried deleting Tinwoo all together and reinstalling it but it's still in Japanese. WTF

Delete tinwoo config file and relaunch it.

**Comment by Spokehedz** [comment]
This is still an issue. Changing the number in the .json is not setting the language properly.
