### ISSUE TITLE
can you add the installation speed display, e.g. 30Mb/s

### ISSUE THREAD

**Issue by lsp199308** [mrdude2478/TinWoo#23]
can you add the installation speed display, e.g. 30Mb/s
thanks

**Comment by mrdude2478** [comment]
Add code and issue a pull request.

**Comment by lsp199308** [comment]
This is included in the code, but is not displayed correctly
![image](https://user-images.githubusercontent.com/77911322/167119020-2bdc4170-39a6-49a1-b4e2-bb465662c0cf.jpeg)
Tinwoo is blank here, no installation information is displayed and installation speed

**Comment by mrdude2478** [comment]
Fixed text position in 1.0.8. Available now.
