### ISSUE TITLE
Can't reinstall my games.

### ISSUE THREAD

**Issue by PeaceMaker2001** [mrdude2478/TinWoo#26]
I was looking to reinstall some games with this app after i borked my last CFW installation, but then I get this:

Failed to install 'TITLE'!

Error code: 0x001fb402

It says it failed to open file system with id and it says partially installed contents can be removed from the System Settings Applet.

I looked in there and I saw nothing. What am I missing here???

```
Failed to install [TITLE]!

Partially installed contents can be removed from the System Settings applet.

OpenFileSystemWithId:112: Failed to open file system with id:
@SdCardContent://registered/000000F6/d33643a3ab96639749ad3ade3424a00e.nca. Error code: 0x001fb402

**Comment by PeaceMaker2001** [comment]
I also looked in the System Settings Applet and found nothing...

**Comment by lsp199308** [comment]
You do not have enough storage space, during the installation process, you need to take double the storage space

**Comment by PeaceMaker2001** [comment]
@lsp199308 I fixed this issue by editing my hekate.ini file. By adding the line 'kip1patch=nosigchk' (exclude quotation marks, obviously), after the line that says 'fss0=[whatevercomesafter]', I was finally able to get it rolling again. Hope this helps anybody. I was legitimately confused..
