### ISSUE TITLE
Crash bug 11.0.0 sxos

### ISSUE THREAD

**Issue by tiansongyu** [mrdude2478/TinWoo#3]
The second time you open the software, it freezes  in 11.0.0 sxos 。
tinleaf also has the same problem。

**Comment by mrdude2478** [comment]
It doesn't crash for me, maybe you have something installed on your switch that is causing it to crash. I am using 11.0.0 + SXOS 3.10, also dual booting the latest Atmosphere (both emunand) and don't have any issues on either firmware. Try using a fresh sd card without any plugins running in the background.

**Comment by tiansongyu** [comment]
Thanks
