### ISSUE TITLE
Failed to Install *Game* 126

### ISSUE THREAD

**Issue by DreamsOfRlyeh** [mrdude2478/TinWoo#31]
Hi there, man, first off, thank you for the services you provide. Second, I do apologize for bothering you through this as its not code related. Tinwoo has proven to be an excellent installer amongst the others that I have tried. Now, enough butt kissing. I have a minor issue. More recently I have had issues with installations, as they all end up with failure and the remark: OpenFileSystemWithld: 126 and error code 0x001fb402.I have updated the sig patches, firmware etc and nothing. I noticed that this happened more so recently with the new atmosphere update, and I am not sure if it's the firmware, or perhaps there this something on this end. I have scoured the internet, but I haven't found anything, so I am hoping that you may be able to shed some light on this. I look forward to hearing from you, take care, man!

**Comment by mrdude2478** [comment]
Try DBI installer and see if the issue persists, it could be down to the NSP/XCI you downloaded as there are recently (in the last few months) many sites that have corrupted NSP files with corrupted tickets.

https://github.com/rashevskyv/dbi/releases

**Comment by DreamsOfRlyeh** [comment]
I have tried DBI multiple times and never succeeded unless there is a
conflict with multiple installers being on the system. But everytime I try
it, the files come out corrupted, even the ones that I have successfully
installed before. On DBI, I tried both MTP Responder and directly into the
SD card with no success. Are there any sites that you suggest, because I
use NXbrew and Nsw2u. Both have had great success rates up until recently.

**Comment by mrdude2478** [comment]
There's been corrupted NSP's comming from those sites, they just copy links from other sites. Also it you can install other NSP's - it's not an issue with the installers. Maybe your SD card is full or corrupted.

**Comment by DreamsOfRlyeh** [comment]
I appreciate you working with me, man! I'm going to go buy a new SD and try
that out. But it's still weird because I can use the same file, say the new
Zelda, on my Steam Deck. So this is a really peculiar issue.

**Comment by DreamsOfRlyeh** [comment]
I'm currently getting ready for work so I cannot provide pictures, but one
of two things will happen, it will either install and then appear as an
infinitely loading grey box, or it'll go into the prompt of it checking to
see that it's corrupted, and after the check it'll say that the card is
corrupted, despite reformatting it to either Fat32 or EXFAT.

**Comment by mrdude2478** [comment]
> @mrdude2478, can you provide examples of corrupted nsps with corrupted tickets from that sites? I never had any issues with that sites.

I don't have any corrupt nsp, The ones I did get that were corrupt, I ended up getting from elsewhere. TBH I've not downloaded any games for quite a while now as most games being released in the last 6 months have been crap.
