### ISSUE TITLE
Error on compiling

### ISSUE THREAD

**Issue by Lukas2288** [mrdude2478/TinWoo#32]
I tried to compile it myself but still getting those error.  Any idea what is wrong

`
source/nx/usbhdd.cpp: In function 'int nx::hdd::entry(void*)':

source/nx/usbhdd.cpp:49:97: error: 'min' is not a member of 'std'
   49 |                         if(!(listed_device_count = usbHsFsListMountedDevices(g_usbDevices, std::min(g_usbDeviceCount, MAX_DEVICES))))
      |                            
                                                                     ^~~
source/nx/usbhdd.cpp: In function 'u32 nx::hdd::count()':

source/nx/usbhdd.cpp:62:29: error: 'min' is not a member of 'std'
   62 |                 return std::min(g_usbDeviceCount, MAX_DEVICES);`

**Comment by mrdude2478** [comment]
Use the Dev Branch for now.
