### ISSUE TITLE
Add support for simple index.html

### ISSUE THREAD

**Issue by vegedb** [mrdude2478/TinWoo#33]
Using rclone to serve http but only tinwoo is unable to see it, tinfoil/dbi/chrome are able to use it.
rclone command `rclone serve http --addr :8080 C:\testfolder`

Here is the index.html. https://github.com/rclone/rclone/blob/5d2e327b6fbec2e821f2b9f942bbaa1fe534c021/cmd/serve/http/data/templates/index.html

### Chrome
![image](https://github.com/mrdude2478/TinWoo/assets/72070424/02e74f75-a7a9-455c-9e0e-a66d6dc31ae7)
### DBI
![image](https://github.com/mrdude2478/TinWoo/assets/72070424/533fc5a3-f2d6-4f57-b3ea-32e3217e4982)
### Tinfoil
![image](https://github.com/mrdude2478/TinWoo/assets/72070424/061415ad-41cf-4965-8735-0c98b0263d42)

## Not Working Tinwoo
![image](https://github.com/mrdude2478/TinWoo/assets/72070424/2bc70397-62e7-4e0e-b3a5-1ea4a3af6e35)

**Comment by mrdude2478** [comment]
html pages don't get downloaded with the curl version I am using, only pages generated by php will work.

In the source - netInstall.cpp, when you use this line of code: ```response = inst::curl::downloadToBuffer(url);``` there is no reponse from an html page (from php there is), I had a look at curl to see if I could figure out why it wouldn't get a response from it, if you were to look at curl in ```opt\devkitpro\portlibs\switch\include\curl``` perhaps you can figure out why as I couldn't find what was causing the issue.

**Comment by mrdude2478** [comment]
@vegedb

Ok, I figured out a workaround now, I'll post a fix for html page dowloads in the next update.

**Comment by vegedb** [comment]
> @vegedb
> 
> Ok, I figured out a workaround now, I'll post a fix for html page dowloads in the next update.

Can't wait!
rclone is the easiest way to install games through PC via wifi without installing proprietary software. 

If you could test even further, i get max speeds of 100mb/s installing through DBI, tried ram mode too.
BUT, on tinfoil, I could install at max wifi speeds switch supports which is around 200mb/s.

**Comment by mrdude2478** [comment]
> > @vegedb
> > Ok, I figured out a workaround now, I'll post a fix for html page dowloads in the next update.
> 
> Can't wait! rclone is the easiest way to install games through PC via wifi without installing proprietary software.
> 
> If you could test even further, i get max speeds of 100mb/s installing through DBI, tried ram mode too. BUT, on tinfoil, I could install at max wifi speeds switch supports which is around 200mb/s.

I've modded the code now so that not only can you scrape the links from an html / text file etc, you can also post links on pastebin or any other site and grab them from there.

Download speed is kind of limited by your server and the host you are downloading from, for me I can install fast from my home server so it's not tinwoo that is causing any issues.

I've just got a few code tweaks left to go and some more testing and I'll do a new release, but you'll be happy with the next version as it's basically got what you asked for now.

**Comment by vegedb** [comment]
> I've modded the code now so that not only can you scrape the links from an html / text file etc, you can also post links on pastebin or any other site such as github etc. and grab them from there.

Latest update broke english language btw, its in japanese even when eng is selected.

However, I've tried adding `http server source URL:http://192.168.1.127:8080` and going go `LAN` install, it shows the same "waiting for connection page".

Auto encode urls for http server installs and base url selected. 
Do i need to have specific folder structure for it to work?

**Comment by mrdude2478** [comment]
> > I've modded the code now so that not only can you scrape the links from an html / text file etc, you can also post links on pastebin or any other site such as github etc. and grab them from there.
> 
> Latest update broke english language btw, its in japanese even when eng is selected.
> 
> However, I've tried adding `http server source URL:http://192.168.1.127:8080` and going go `LAN` install, it shows the same "waiting for connection page".
> 
> Auto encode urls for http server installs and base url selected. Do i need to have specific folder structure for it to work?

Delete your config file from the tinwoo directory - I changed code in the langauge files so your config file probably has 99 in it, this no longer exists. Once you do that and restart tinwoo the language will be in English. Enable base url if you home server href links look like this:

```
Disable base url link
<a href="http://192.168.1.127/Games/xgame.nsp">

Enable base url link
<a href="http://192.168.1.127/Games/xgame.nsp">

Encode url + Disable base url link (noitce spaces etc in game the link)
<a href="http://192.168.1.127/Games/xgame [ ] xxx.nsp">

Enable base url link + disable encode url link
<a href="Games/Sonic%20Mania%20[01009AA000FAA000]%20[Version%201.04].xcz>
```

Also I only tried on port 80, I didn't try a url with the post added http://xxx.xxx.xx:8080 - it could be that the : is being encoded - I'll test later.
