### ISSUE TITLE
Touching the select all button only selects the highlited file

### ISSUE THREAD

**Issue by marius137** [mrdude2478/TinWoo#34]
When uploading multiple files via lan using ns-usbloader and tapping the select all button on the touchscreen only the highlighted file gets selected

**Comment by mrdude2478** [comment]
> When uploading multiple files via lan using ns-usbloader and tapping the select all button on the touchscreen only the highlighted file gets selected

It's working on my end - I just tried with 4 files and pressed Y and all files highlight and unhighlight properly. How many files are you trying to install at once?

**Comment by marius137** [comment]
I was in fact trying to use the touchscreen. I am surprised it works that well without any touchscreen support.

**Comment by mrdude2478** [comment]
> I was in fact trying to use the touchscreen. I am surprised it works that well without any touchscreen support.

It works, but only for selecting items from the the lists - to do what you want would mean coding the screen co-ords into each page for each bit of text and each language is different so these would change the co-ords for each language. I don't have any motivation to do this as I have other stuff I am working on, maybe if you code that yourself then test it for each language and add it as a PR it will be added.
