### ISSUE TITLE
No English

### ISSUE THREAD

**Issue by Bossiskeyboard** [mrdude2478/TinWoo#37]
When I try to set Tinwoo to english it just keeps being japanese

**Comment by mrdude2478** [comment]
I found the problem now, If your switch region was not Europe or Australia you will get the japanese issue. I've fixed it now and will push a git update later today.

**Comment by hax4dazy** [comment]
> If your switch region was not Europe or Australia 
My switch region was set to Roper but I still had the issue occur?

**Comment by mirivedan** [comment]
Went well for me too
