### ISSUE TITLE
Request: Add TinWoo to HB App Store

### ISSUE THREAD

**Issue by MadTooth** [mrdude2478/TinWoo#39]
Can you add TinWoo to the [HB App Store](https://github.com/fortheusers/hb-appstore) ?

**Comment by mrdude2478** [comment]
You would need to ask the HB app store dev to do that.

**Comment by MadTooth** [comment]
You are the owner, you decide whether it is necessary or not [[send a request](https://submit.fortheusers.org/)]

**Comment by mrdude2478** [comment]
OK I've thought about it, I can't be bothered to fill in all that website page stuff you linked to, so the answer is no for now.

**Comment by MadTooth** [comment]
> OK I've thought about it, I can't be bothered to fill in all that website page stuff you linked to, so the answer is no for now.

5-10 minute
