### ISSUE TITLE
Slow http speed compared to Tinfoil

### ISSUE THREAD

**Issue by vegedb** [mrdude2478/TinWoo#40]
First of all, thanks for fixing/adding http support!

But there's a speed problem using TinWoo.

## Using Tinfoil
![image](https://github.com/mrdude2478/TinWoo/assets/72070424/54eb5d08-bc13-43a1-9d00-a26d684c63ed)

## Using TinWoo
![image](https://github.com/mrdude2478/TinWoo/assets/72070424/7d5a3199-43af-4098-9adc-55c9207bca4b)

# Explanation

1. **Same** file used
2. **Same** HTTP server
3. **Same** 5Ghz wifi network
4. **Same** Switch
5. Tests performed only 5-10 minutes apart

As you can see from the pictures, tinfoil is maxing switch's 5ghz speeds at 20MB/s. 
TinWoo has a problem where it doesn't get above 10MB/s much less 20.

**Comment by vegedb** [comment]
![image](https://github.com/mrdude2478/TinWoo/assets/72070424/4b44ce04-a4a6-4bd0-9744-53d995887154)

During install, these are the hardware stats, maybe this will be helpful for you to figure out the problem.

**Comment by mrdude2478** [comment]
Weird, the first test I tried on wireless I was getting higher speeds:

![image]https://i.imgur.com/8POIWHt.png

I'm doing theme stuff just now so won't be looking into this soon, maybe tinfoil is using multithreading for downloading? Did you look at the tinwoo code yourself to try and figure this out?

**Comment by vegedb** [comment]
> maybe tinfoil is using multithreading for downloading? 

https://github.com/XorTroll/Goldleaf/commit/7df660e2fe636daaad12258a29f152a6d52dc9e1?diff=split

Perhaps this might help.

**Comment by mrdude2478** [comment]
> > maybe tinfoil is using multithreading for downloading?
> 
> [XorTroll/Goldleaf@7df660e?diff=split](https://github.com/XorTroll/Goldleaf/commit/7df660e2fe636daaad12258a29f152a6d52dc9e1?diff=split)
> 
> Perhaps this might help.

I appreciate you are trying to help, so don't take this the wrong way. I am busy just now and have other things I am doing. If you want to fix this yourself download the code and look at it. Once I am finished with the theme stuff I am doing I am moving onto other projects so will not be looking at this code for a good while. In the meantime just use tinleaf or dbi if speed is an issue for you. TBH it's a low priority for me, but if you find out what the issue it put in a pull request and i'll look at it.

**Comment by vegedb** [comment]
> > > maybe tinfoil is using multithreading for downloading?
> > 
> > 
> > [XorTroll/Goldleaf@7df660e?diff=split](https://github.com/XorTroll/Goldleaf/commit/7df660e2fe636daaad12258a29f152a6d52dc9e1?diff=split)
> > Perhaps this might help.
> 
> I appreciate you are trying to help, so don't take this the wrong way. I am busy just now and have other things I am doing. If you want to fix this yourself download the code and look at it. Once I am finished with the theme stuff I am doing I am moving onto other projects so will not be looking at this code for a good while. In the meantime just use tinleaf or dbi if speed is an issue for you. TBH it's a low priority for me, but if you find out what the issue it put in a pull request and i'll look at it.

No worries, you have no obligation to do it in a rush, I'm just reporting it as I go along.

DBI = has the same issue as TinWoo of not going above 20MB/s, made an issue a year ago and he has no idea how to fix it either, so dead end there.
Goldleaf = NO http support
Tinleaf =  Outdated fork of awoo and yours is much better.


So far tinfoil is the fastest way, pity its closed source though.

**Comment by mrdude2478** [comment]
> > > > maybe tinfoil is using multithreading for downloading?
> > > 
> > > 
> > > [XorTroll/Goldleaf@7df660e?diff=split](https://github.com/XorTroll/Goldleaf/commit/7df660e2fe636daaad12258a29f152a6d52dc9e1?diff=split)
> > > Perhaps this might help.
> > 
> > 
> > I appreciate you are trying to help, so don't take this the wrong way. I am busy just now and have other things I am doing. If you want to fix this yourself download the code and look at it. Once I am finished with the theme stuff I am doing I am moving onto other projects so will not be looking at this code for a good while. In the meantime just use tinleaf or dbi if speed is an issue for you. TBH it's a low priority for me, but if you find out what the issue it put in a pull request and i'll look at it.
> 
> No worries, you have no obligation to do it in a rush, I'm just reporting it as I go along.
> 
> DBI = has the same issue as TinWoo of not going above 20MB/s, made an issue a year ago and he has no idea how to fix it either, so dead end there. Goldleaf = NO http support Tinleaf = Outdated fork of awoo and yours is much better.
> 
> So far tinfoil is the fastest way, pity its closed source though.

I was getting ok speed considering I was serving via a rasperry pi 2 that is reading from a micro sd card, I'll try serving from a NAS later straight from SSD to see if it makes a difference, which I suspect it will. Even still I was getting over 11MB via a server using a micro sd card to store files and that's also running the pi software so I don't expect it to be that fast.

**Comment by mrdude2478** [comment]
I had a look at curl, which is responsible for downloading. This is about as good as it can get for now. Tinleaf might be making multiple connections at the same time (the same as some download managers) and downloading in parts - then joining them together, however to do this in Tinwoo would break lots of code and need lots of mods to the progress bar code which is part of plutonium. The curl version I am using is only making 1 connection and the speed is maxed out with this already (unless I missed some setting to make it faster), I don't have the time of willpower to make these mods that you want. Also I tried downloading from different servers, one which was using a hard drive (NAS), one with and sd card (Ri Pi 4), one with an SSD (RI Pi 4). The Pi 4 with the ssd gave the best speeds which was around 20MBPS, the NAS with a hard drive (synology 212+) was around 14MBPS, The pi2 with the sd card was around 11-12 MBPS. I suggest you try using on a fast server as that makes a difference. For now I will close this issue as it's not really a coding issue. If you need faster download speeds - use tinleaf.
