### ISSUE TITLE
Multiple settings options borked in latetst version

### ISSUE THREAD

**Issue by eyeonus** [mrdude2478/TinWoo#45]
v1.0.23, multiple settings are prefaced with "didn't find":
![2023101319171300_s](https://github.com/mrdude2478/TinWoo/assets/1733600/33b4a72d-dfba-4822-9601-3ba11a72edbb)
![2023101319171800_s](https://github.com/mrdude2478/TinWoo/assets/1733600/8ecf8938-5467-4d8a-8d90-6725cf7547f8)

**Comment by mrdude2478** [comment]
Remove the theme directory from your switch tinwoo folder and redownload the theme. This informationis in the release page.

**Comment by eyeonus** [comment]
I do not have a theme directory.
![2023101402463100-942DAC639CA710FF6C0B4F2AA969B120](https://github.com/mrdude2478/TinWoo/assets/1733600/c1bd8068-9afc-4dab-8f9a-d7066cf262d2)

**Comment by mrdude2478** [comment]
Remove everything in that folder apart from tinwoo.nro.

**Comment by eyeonus** [comment]
> Completely erasing everything and re-installing has fixed the problem, however, I feel it prudent to point out that it is not good practice to close issues that have not been resolved.

I see you completely missed the part where I mentioned I had already fixed it myself.

As to your condescension, I feel you misunderstand. I don't care that you're a complete ass, I just felt it appropriate to mention that being an ass does not do you any favors.

I feel I should mention that you and I are in the same generation, and your assumption that I and my peers are "woke" is downright laughable. There is a difference between being polite and being indulgent. You are obviously neither.

Leave your culture war politics at home, bruv.
