### ISSUE TITLE
Can the highlighted thing be... a bit more highlighted?

### ISSUE THREAD

**Issue by Clydefrosch22** [mrdude2478/TinWoo#7]
Black on black is hard to see, maybe the highlighted thing could be made a bit more bright?

**Comment by mrdude2478** [comment]
Maybe you need to adjust your TV contrast/brightness levels as it works fine for me and is easy to see.

**Comment by Clydefrosch22** [comment]
i only ever use this in handheld mode and it's really not optimal
https://camo.githubusercontent.com/223185e778c26f32d982caf849986d2ab2e3279806dfe5a32a9c77d884758204/68747470733a2f2f692e696d6775722e636f6d2f366f5a4f5538482e6a7067
even in the screenshot it's really all but optimal
