### ISSUE TITLE
[Localization updated] Traditional Chinese langs for v1.0.1

### ISSUE THREAD

**Issue by qazrfv1234** [mrdude2478/TinWoo#8]
Hello,
the attachment for TinWoo v1.0.1(the latest en.json )

[zh-rTW lang for Tinwoo v1.0.1.zip](https://github.com/mrdude2478/TinWoo/files/6027543/zh-rTW.lang.for.Tinwoo.v1.0.1.zip)

Many thanks,
Leo

**Comment by mrdude2478** [comment]
Added to test build - will upload later.
