### ISSUE TITLE
Fork of Awoo-Installer

### ISSUE THREAD

**Issue by StudioEtrange** [mrdude2478/TinWoo#9]
It seems to be a fork of  https://github.com/Huntereb/Awoo-Installer

For people understanding, could you mention it on your README and describe what is the difference between this fork and the original repo

Thx

**Comment by mrdude2478** [comment]
It's a combined version of Tinleaf and Awoo with some other added changes such as skinning ability and different file system support for usb connected hard drives.

**Comment by anthr76** [comment]
Is it possible to have a file browser of URL?
